"""Tests for the FLT subprocess env builder in edog.py.

The QA Testing Tool's V2 capability probe needs ``AZURE_OPENAI_*``
variables to be visible to the FLT child process. Before this loader,
``edog.py`` called ``subprocess.Popen(...)`` without an ``env=`` argument,
so the FLT child only inherited the shell env that launched ``edog.py``.
Users who put their credentials in a repo-root ``.env`` file got silent
legacy LLM fallback every time.

These tests pin three properties of the new loader:
  • ``.env`` keys are merged into the subprocess env.
  • Shell env wins over ``.env`` (so explicit user overrides survive).
  • ``AZURE_OPENAI_PRO_*`` is aliased to ``AZURE_OPENAI_*`` when the base
    isn't set (the Editor probe's fallback chain doesn't include PRO).
"""

import importlib.util
import sys
from pathlib import Path

import pytest

PROJECT_DIR = Path(__file__).resolve().parents[1]
EDOG_PY = PROJECT_DIR / "edog.py"


@pytest.fixture(scope="module")
def edog():
    spec = importlib.util.spec_from_file_location("edog_dotenv_loader", EDOG_PY)
    mod = importlib.util.module_from_spec(spec)
    sys.path.insert(0, str(EDOG_PY.parent))
    try:
        spec.loader.exec_module(mod)
    finally:
        sys.path.pop(0)
    return mod


# ── _parse_dotenv_file ───────────────────────────────────────────────────


def test_parse_dotenv_empty_file_returns_empty_dict(edog, tmp_path):
    env_file = tmp_path / ".env"
    env_file.write_text("", encoding="utf-8")
    assert edog._parse_dotenv_file(env_file) == {}


def test_parse_dotenv_missing_file_returns_empty_dict(edog, tmp_path):
    """Loader MUST NOT throw on missing .env — Azure OpenAI credentials
    are optional and many users will not have them configured."""
    assert edog._parse_dotenv_file(tmp_path / ".env") == {}


def test_parse_dotenv_basic_pairs(edog, tmp_path):
    env_file = tmp_path / ".env"
    env_file.write_text(
        "AZURE_OPENAI_ENDPOINT=https://aoai.test/\n"
        "AZURE_OPENAI_API_KEY=sk-1234\n",
        encoding="utf-8",
    )
    result = edog._parse_dotenv_file(env_file)
    assert result["AZURE_OPENAI_ENDPOINT"] == "https://aoai.test/"
    assert result["AZURE_OPENAI_API_KEY"] == "sk-1234"


def test_parse_dotenv_strips_quotes(edog, tmp_path):
    env_file = tmp_path / ".env"
    env_file.write_text(
        'AZURE_OPENAI_ENDPOINT="https://aoai.test/"\n'
        "AZURE_OPENAI_API_KEY='sk-1234'\n",
        encoding="utf-8",
    )
    result = edog._parse_dotenv_file(env_file)
    assert result["AZURE_OPENAI_ENDPOINT"] == "https://aoai.test/"
    assert result["AZURE_OPENAI_API_KEY"] == "sk-1234"


def test_parse_dotenv_skips_comments_and_blanks(edog, tmp_path):
    env_file = tmp_path / ".env"
    env_file.write_text(
        "# Top-of-file comment\n"
        "\n"
        "AZURE_OPENAI_ENDPOINT=https://aoai.test/\n"
        "# inline-style comment block\n"
        "AZURE_OPENAI_API_KEY=sk-1234\n"
        "\n",
        encoding="utf-8",
    )
    result = edog._parse_dotenv_file(env_file)
    assert set(result.keys()) == {"AZURE_OPENAI_ENDPOINT", "AZURE_OPENAI_API_KEY"}


def test_parse_dotenv_supports_export_prefix(edog, tmp_path):
    """Some teams check in .env files generated by ``env > .env`` which
    prefixes ``export``; the loader should accept that form."""
    env_file = tmp_path / ".env"
    env_file.write_text("export AZURE_OPENAI_ENDPOINT=https://aoai.test/\n", encoding="utf-8")
    result = edog._parse_dotenv_file(env_file)
    assert result["AZURE_OPENAI_ENDPOINT"] == "https://aoai.test/"


# ── _build_flt_subprocess_env ────────────────────────────────────────────


def test_build_flt_env_includes_dotenv_keys(edog, tmp_path):
    (tmp_path / ".env").write_text(
        "AZURE_OPENAI_PRO_ENDPOINT=https://pro.test/\n"
        "AZURE_OPENAI_PRO_API_KEY=sk-pro\n",
        encoding="utf-8",
    )
    env = edog._build_flt_subprocess_env(tmp_path, base_env={"PATH": "/usr/bin"})
    assert env["PATH"] == "/usr/bin"
    assert env["AZURE_OPENAI_PRO_ENDPOINT"] == "https://pro.test/"
    assert env["AZURE_OPENAI_PRO_API_KEY"] == "sk-pro"


def test_build_flt_env_shell_wins_over_dotenv(edog, tmp_path):
    """If the user exported a var in their shell, the .env MUST NOT
    override it — explicit user intent beats repo config."""
    (tmp_path / ".env").write_text("AZURE_OPENAI_ENDPOINT=https://from-dotenv.test/\n", encoding="utf-8")
    env = edog._build_flt_subprocess_env(
        tmp_path,
        base_env={"AZURE_OPENAI_ENDPOINT": "https://from-shell.test/"},
    )
    assert env["AZURE_OPENAI_ENDPOINT"] == "https://from-shell.test/"


def test_build_flt_env_aliases_pro_to_base_when_base_missing(edog, tmp_path):
    """The Editor probe's fallback chain looks up AZURE_OPENAI_ENDPOINT /
    AZURE_OPENAI_API_KEY — there is no PRO step in its chain. The loader
    must alias PRO → base so an Editor-less .env still reaches a working
    endpoint."""
    (tmp_path / ".env").write_text(
        "AZURE_OPENAI_PRO_ENDPOINT=https://pro.test/\n"
        "AZURE_OPENAI_PRO_API_KEY=sk-pro\n"
        "AZURE_OPENAI_PRO_API_VERSION=2025-04-01-preview\n"
        "AZURE_OPENAI_PRO_DEPLOYMENT=gpt-5.4\n",
        encoding="utf-8",
    )
    env = edog._build_flt_subprocess_env(tmp_path, base_env={})
    assert env["AZURE_OPENAI_ENDPOINT"] == "https://pro.test/"
    assert env["AZURE_OPENAI_API_KEY"] == "sk-pro"
    assert env["AZURE_OPENAI_API_VERSION"] == "2025-04-01-preview"
    assert env["AZURE_OPENAI_DEPLOYMENT"] == "gpt-5.4"


def test_build_flt_env_does_not_alias_when_base_already_set(edog, tmp_path):
    """If the .env declares both PRO and base explicitly (some teams keep
    distinct keys for Architect vs Editor), the loader MUST NOT clobber
    the base with PRO."""
    (tmp_path / ".env").write_text(
        "AZURE_OPENAI_PRO_ENDPOINT=https://pro.test/\n"
        "AZURE_OPENAI_ENDPOINT=https://base.test/\n",
        encoding="utf-8",
    )
    env = edog._build_flt_subprocess_env(tmp_path, base_env={})
    assert env["AZURE_OPENAI_ENDPOINT"] == "https://base.test/"
    assert env["AZURE_OPENAI_PRO_ENDPOINT"] == "https://pro.test/"


def test_start_flt_service_passes_env_to_popen(edog):
    """Source-grep pin: start_flt_service MUST pass env= to Popen, with
    the env coming from _build_flt_subprocess_env. Without this, the
    fix above doesn't actually reach the FLT process."""
    src = EDOG_PY.read_text(encoding="utf-8")
    assert "_build_flt_subprocess_env(" in src, (
        "start_flt_service must build a merged env via _build_flt_subprocess_env."
    )
    assert "env=flt_env" in src, (
        "subprocess.Popen for FLT must pass env=flt_env so the child sees AZURE_OPENAI_* keys."
    )
